"""Add Act model and Tag model

Revision ID: 9f7ba031830c
Revises: 
Create Date: 2024-11-26 13:35:04.519646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7ba031830c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acts',
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('du_code', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('journal_no', sa.Integer(), nullable=False),
    sa.Column('num_edits', sa.Integer(), nullable=False),
    sa.Column('text_payload', sa.Text(), nullable=False),
    sa.Column('date_scraped', sa.Date(), nullable=False),
    sa.Column('last_edited_date', sa.Date(), nullable=True),
    sa.Column('last_tag_added_date', sa.Date(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('part_no', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('act_id')
    )
    op.create_table('acts_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('act_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('assigner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['act_id'], ['acts.act_id'], ),
    sa.ForeignKeyConstraint(['assigner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('acts_tags')
    op.drop_table('acts')
    # ### end Alembic commands ###
